import {
  ExpenditureProps,
  IncomeProps,
} from "@sparcs-students/web/features/document-lookup/budget/type/viewerReviewerTableValues";
import {
  BudgetClassExpenseEnum,
  BudgetDivisionExpenseEnum,
  BudgetDivisionIncomeEnum,
  BudgetDomainEnum,
  DocumentReviewStatusEnum,
} from "@sparcs-students/root/packages/interface/src/common/enum";

export const mockExpenditureData: ExpenditureProps[] = [
  {
    code: 401,
    id: 0,
    budgetDomain: BudgetDomainEnum.Student,
    budgetDivisionExpense: BudgetDivisionExpenseEnum.Operating,
    name: "격려금",
    item: BudgetClassExpenseEnum.Product,
    lastYear: 125000,
    thisYear: 125000,
    ratio: 100.0,
    reason: "대충 어쩌구저쩌구한 근거\n아무말이나 적자\nㅁㄴㅇㄹ",
    status: DocumentReviewStatusEnum.Accepted,
    review: "",
  },
  {
    code: 402,
    id: 1,
    budgetDomain: BudgetDomainEnum.Student,
    budgetDivisionExpense: BudgetDivisionExpenseEnum.Operating,
    name: "격려금",
    item: BudgetClassExpenseEnum.Product,
    lastYear: 12500,
    thisYear: 125000,
    ratio: 1000.0,
    reason: "대충 어쩌구저쩌구한 근거\n아무말이나 적자\nㅁㄴㅇㄹ",
    status: DocumentReviewStatusEnum.ReviseNeeded,
    review: "",
  },
  {
    code: 403,
    id: 2,
    budgetDomain: BudgetDomainEnum.Student,
    budgetDivisionExpense: BudgetDivisionExpenseEnum.Operating,
    name: "격려금",
    item: BudgetClassExpenseEnum.Product,
    lastYear: 125000,
    thisYear: 125000,
    ratio: 100.0,
    reason: "대충 어쩌구저쩌구한 근거\n아무말이나 적자\nㅁㄴㅇㄹ",
    status: DocumentReviewStatusEnum.Rejected,
    review: "",
  },
  {
    code: 501,
    id: 3,
    budgetDomain: BudgetDomainEnum.School,
    budgetDivisionExpense: BudgetDivisionExpenseEnum.Operating,
    name: "격려금",
    item: BudgetClassExpenseEnum.Product,
    lastYear: 125000,
    thisYear: 125000,
    ratio: 100.0,
    reason: "대충 어쩌구저쩌구한 근거\n아무말이나 적자\nㅁㄴㅇㄹ",
    status: DocumentReviewStatusEnum.Accepted,
    review: "",
  },
];

export const mockIncomeData: IncomeProps[] = [
  {
    code: 101,
    id: 0,
    budgetDomain: BudgetDomainEnum.Student,
    budgetDivisionIncome: BudgetDivisionIncomeEnum.Substratum,
    item: "기층기구회계 지원금",
    lastYear: 125000,
    thisYear: 125000,
    ratio: 100.0,
    reason:
      "대충 어쩌구저쩌구한 비고\n아무말이나 적자\nㅁㄴㅇㄹ\nㅁㄴㅇㄻㄴㅇㄹ",
    status: DocumentReviewStatusEnum.Accepted,
    review: "",
  },
  {
    code: 102,
    id: 1,
    budgetDomain: BudgetDomainEnum.Student,
    budgetDivisionIncome: BudgetDivisionIncomeEnum.Substratum,
    item: "기층기구회계 지원금",
    lastYear: 125000,
    thisYear: 125000,
    ratio: 100.0,
    reason:
      "대충 어쩌구저쩌구한 비고\n아무말이나 적자\nㅁㄴㅇㄹ\nㅁㄴㅇㄻㄴㅇㄹ",
    status: DocumentReviewStatusEnum.Accepted,
    review: "",
  },
  {
    code: 103,
    id: 2,
    budgetDomain: BudgetDomainEnum.Student,
    budgetDivisionIncome: BudgetDivisionIncomeEnum.Substratum,
    item: "기층기구회계 지원금",
    lastYear: 125000,
    thisYear: 150000,
    ratio: 120.0,
    reason:
      "대충 어쩌구저쩌구한 비고\n아무말이나 적자\nㅁㄴㅇㄹ\nㅁㄴㅇㄻㄴㅇㄹ",
    status: DocumentReviewStatusEnum.Accepted,
    review: "",
  },
  {
    code: 201,
    id: 3,
    budgetDomain: BudgetDomainEnum.School,
    budgetDivisionIncome: BudgetDivisionIncomeEnum.School,
    item: "기층기구회계 지원금",
    lastYear: 125000,
    thisYear: 150000,
    ratio: 100.0,
    reason:
      "대충 어쩌구저쩌구한 비고\n아무말이나 적자\nㅁㄴㅇㄹ\nㅁㄴㅇㄻㄴㅇㄹ",
    status: DocumentReviewStatusEnum.Accepted,
    review: "",
  },
];
