import {
  BudgetClassExpenseEnum,
  BudgetDivisionExpenseEnum,
  BudgetDivisionIncomeEnum,
  BudgetDomainEnum,
} from "@sparcs-students/root/packages/interface/src/common/enum/budget.enum";
import { DocumentReviewStatusEnum } from "@sparcs-students/root/packages/interface/src/common/enum/meeting.enum";
import {
  ManagerExpenditureProps,
  ManagerIncomeProps,
  ManagerProjectNameCandidate,
} from "@sparcs-students/web/features/document-lookup/budget/type/managerFormValues";

export const mockManagerIncomeData: ManagerIncomeProps[] = [
  {
    code: 0,
    id: 0,
    budgetDomain: BudgetDomainEnum.Undefined,
    budgetDivisionIncome: BudgetDivisionIncomeEnum.Undefined,
    item: "",
    lastYear: "",
    thisYear: "",
    ratio: 100.0,
    reason: "",
    status: DocumentReviewStatusEnum.Unsaved,
    review: "",
  },
];

export const mockManagerExpenditureData: ManagerExpenditureProps[] = [
  {
    code: 401,
    id: 0,
    rowId: 0,
    budgetDomain: BudgetDomainEnum.Student,
    budgetDivisionExpenditure: BudgetDivisionExpenseEnum.Operating,
    projectName: "격려금",
    item: BudgetClassExpenseEnum.Product,
    lastYear: "125000",
    thisYear: "125000",
    ratio: 100.0,
    reason: "",
    status: DocumentReviewStatusEnum.Unsaved,
    review: "",
  },
  {
    code: 401,
    id: 1,
    rowId: 1,
    budgetDomain: BudgetDomainEnum.Student,
    budgetDivisionExpenditure: BudgetDivisionExpenseEnum.Operating,
    projectName: "어떠한 지출",
    item: BudgetClassExpenseEnum.Product,
    lastYear: "500000",
    thisYear: "600000",
    ratio: 120.0,
    reason: "어떠한 사업을 위한 지출입니다.",
    status: DocumentReviewStatusEnum.Unsaved,
    review: "",
  },
  {
    code: 501,
    id: 2,
    rowId: 2,
    budgetDomain: BudgetDomainEnum.School,
    budgetDivisionExpenditure: BudgetDivisionExpenseEnum.Operating,
    projectName: "어떠한 지출",
    item: BudgetClassExpenseEnum.Product,
    lastYear: "500000",
    thisYear: "600000",
    ratio: 120.0,
    reason: "어떠한 사업을 위한 지출입니다.",
    status: DocumentReviewStatusEnum.Unsaved,
    review: "",
  },
  {
    code: 601,
    id: 3,
    rowId: 3,
    budgetDomain: BudgetDomainEnum.Autonomous,
    budgetDivisionExpenditure: BudgetDivisionExpenseEnum.Operating,
    projectName: "어떠한 지출",
    item: BudgetClassExpenseEnum.Product,
    lastYear: "500000",
    thisYear: "600000",
    ratio: 120.0,
    reason: "어떠한 사업을 위한 지출입니다.",
    status: DocumentReviewStatusEnum.Unsaved,
    review: "",
  },
  {
    code: 501,
    id: 4,
    rowId: 4,
    budgetDomain: BudgetDomainEnum.School,
    budgetDivisionExpenditure: BudgetDivisionExpenseEnum.New,
    projectName: "학기 초 오리엔테이션",
    item: BudgetClassExpenseEnum.Supply,
    lastYear: "0",
    thisYear: "300000",
    ratio: null,
    reason: "기념품 및 물품 제작",
    status: DocumentReviewStatusEnum.Unsaved,
    review: "",
  },
  {
    code: 502,
    id: 5,
    rowId: 5,
    budgetDomain: BudgetDomainEnum.School,
    budgetDivisionExpenditure: BudgetDivisionExpenseEnum.New,
    projectName: "학기 초 오리엔테이션",
    item: BudgetClassExpenseEnum.Labor,
    lastYear: "0",
    thisYear: "200000",
    ratio: null,
    reason: "행사 대행 업체 섭외 비용",
    status: DocumentReviewStatusEnum.Unsaved,
    review: "",
  },
  {
    code: 501,
    id: 6,
    rowId: 6,
    budgetDomain: BudgetDomainEnum.School,
    budgetDivisionExpenditure: BudgetDivisionExpenseEnum.New,
    projectName: "중간고사 집중 학습 지원",
    item: BudgetClassExpenseEnum.Supply,
    lastYear: "0",
    thisYear: "150000",
    ratio: null,
    reason: "조명 개선",
    status: DocumentReviewStatusEnum.Unsaved,
    review: "",
  },
  {
    code: 502,
    id: 7,
    rowId: 7,
    budgetDomain: BudgetDomainEnum.School,
    budgetDivisionExpenditure: BudgetDivisionExpenseEnum.New,
    projectName: "중간고사 집중 학습 지원",
    item: BudgetClassExpenseEnum.Supply,
    lastYear: "0",
    thisYear: "250000",
    ratio: null,
    reason: "스터디존 확보",
    status: DocumentReviewStatusEnum.Unsaved,
    review: "",
  },
  {
    code: 503,
    id: 8,
    rowId: 8,
    budgetDomain: BudgetDomainEnum.School,
    budgetDivisionExpenditure: BudgetDivisionExpenseEnum.New,
    projectName: "중간고사 집중 학습 지원",
    item: BudgetClassExpenseEnum.Product,
    lastYear: "0",
    thisYear: "100000",
    ratio: null,
    reason: "간식 제공",
    status: DocumentReviewStatusEnum.Unsaved,
    review: "",
  },
  {
    code: 601,
    id: 9,
    rowId: 9,
    budgetDomain: BudgetDomainEnum.Autonomous,
    budgetDivisionExpenditure: BudgetDivisionExpenseEnum.Operating,
    projectName: "학생회 문화의 밤",
    item: BudgetClassExpenseEnum.Welfare,
    lastYear: "0",
    thisYear: "400000",
    ratio: null,
    reason: "행사 기획 및 운영",
    status: DocumentReviewStatusEnum.Unsaved,
    review: "",
  },
  {
    code: 602,
    id: 10,
    rowId: 10,
    budgetDomain: BudgetDomainEnum.Autonomous,
    budgetDivisionExpenditure: BudgetDivisionExpenseEnum.Operating,
    projectName: "학생회 문화의 밤",
    item: BudgetClassExpenseEnum.Product,
    lastYear: "0",
    thisYear: "200000",
    ratio: null,
    reason: "행사 홍보 및 소품 구입",
    status: DocumentReviewStatusEnum.Unsaved,
    review: "",
  },
];

export const mockManagerProjectNameCandidateList: ManagerProjectNameCandidate[] =
  [
    {
      budgetDomain: BudgetDomainEnum.School,
      budgetDivisionExpenditure: BudgetDivisionExpenseEnum.New,
      projectNameCandidate: ["작년의 어떠한 사업", "작년의 저떠한 사업"],
    },
    {
      budgetDomain: BudgetDomainEnum.Student,
      budgetDivisionExpenditure: BudgetDivisionExpenseEnum.Operating,
      projectNameCandidate: ["작년의 어떠한 사업", "작년의 저떠한 사업"],
    },
    {
      budgetDomain: BudgetDomainEnum.Autonomous,
      budgetDivisionExpenditure: BudgetDivisionExpenseEnum.Operating,
      projectNameCandidate: ["작년의 어떠한 사업", "작년의 저떠한 사업"],
    },
  ];
