import {
  BudgetClassExpenseEnum,
  BudgetDivisionExpenseEnum,
  BudgetDivisionIncomeEnum,
  BudgetDomainEnum,
} from "@sparcs-students/root/packages/interface/src/common/enum/budget.enum";
import { DocumentReviewStatusEnum } from "@sparcs-students/root/packages/interface/src/common/enum/meeting.enum";
import {
  DBExpenditureProps,
  DBIncomeProps,
  ProjectNameCandidate,
} from "@sparcs-students/web/features/document-lookup/budget/type/managerFormValues";

import { ProjectProposalSingleContent } from "@sparcs-students/web/features/document-lookup/project/services/_mock/mockProjectProposalTable";

export const mockDBIncomeData: DBIncomeProps[] = [
  {
    id: 0,
    code: 101,
    budgetDomain: BudgetDomainEnum.Student,
    budgetDivisionIncome: BudgetDivisionIncomeEnum.Substratum,
    item: "학생회비 기층기구",
    lastYear: "100000",
    thisYear: "120000",
    ratio: 120.0,
    reason: "증가된 활동 반영",
    status: DocumentReviewStatusEnum.Progress,
    review: "",
  },
  {
    id: 1,
    code: 102,
    budgetDomain: BudgetDomainEnum.Student,
    budgetDivisionIncome: BudgetDivisionIncomeEnum.Central,
    item: "학생회비 중앙회계",
    lastYear: "200000",
    thisYear: "200000",
    ratio: 100.0,
    reason: "",
    status: DocumentReviewStatusEnum.Progress,
    review: "",
  },
  {
    id: 2,
    code: 201,
    budgetDomain: BudgetDomainEnum.School,
    budgetDivisionIncome: BudgetDivisionIncomeEnum.School,
    item: "학교지원금",
    lastYear: "500000",
    thisYear: "550000",
    ratio: 110.0,
    reason: "지원금 증가",
    status: DocumentReviewStatusEnum.Progress,
    review: "",
  },
  {
    id: 3,
    code: 202,
    budgetDomain: BudgetDomainEnum.School,
    budgetDivisionIncome: BudgetDivisionIncomeEnum.School,
    item: "이월금",
    lastYear: "30000",
    thisYear: "30000",
    ratio: 100.0,
    reason: "",
    status: DocumentReviewStatusEnum.Progress,
    review: "",
  },
  {
    id: 4,
    code: 301,
    budgetDomain: BudgetDomainEnum.Autonomous,
    budgetDivisionIncome: BudgetDivisionIncomeEnum.CAC,
    item: "문화자치기금",
    lastYear: "150000",
    thisYear: "180000",
    ratio: 120.0,
    reason: "행사 확대",
    status: DocumentReviewStatusEnum.Progress,
    review: "",
  },
  {
    id: 5,
    code: 302,
    budgetDomain: BudgetDomainEnum.Autonomous,
    budgetDivisionIncome: BudgetDivisionIncomeEnum.Extra,
    item: "기타수익금",
    lastYear: "50000",
    thisYear: "60000",
    ratio: 120.0,
    reason: "공동수익사업",
    status: DocumentReviewStatusEnum.Progress,
    review: "",
  },
];

export const mockDBExpenditureData: DBExpenditureProps[] = [
  {
    code: 401,
    id: 0,
    rowId: 0,
    budgetDomain: BudgetDomainEnum.Student,
    budgetDivisionExpenditure: BudgetDivisionExpenseEnum.Operating,
    projectName: "어떠한 사업",
    item: BudgetClassExpenseEnum.Product,
    lastYear: "125000",
    thisYear: "125000",
    ratio: 100.0,
    reason: "",
    status: DocumentReviewStatusEnum.Accepted,
    review: "",
  },
  {
    code: 402,
    id: 1,
    rowId: 1,
    budgetDomain: BudgetDomainEnum.Student,
    budgetDivisionExpenditure: BudgetDivisionExpenseEnum.Regular,
    projectName: "어떠한 사업",
    item: BudgetClassExpenseEnum.Product,
    lastYear: "500000",
    thisYear: "600000",
    ratio: 120.0,
    reason: "어떠한 사업을 위한 지출입니다.",
    status: DocumentReviewStatusEnum.Accepted,
    review: "",
  },
  {
    code: 501,
    id: 2,
    rowId: 2,
    budgetDomain: BudgetDomainEnum.School,
    budgetDivisionExpenditure: BudgetDivisionExpenseEnum.Operating,
    projectName: "어떠한 사업",
    item: BudgetClassExpenseEnum.Product,
    lastYear: "500000",
    thisYear: "600000",
    ratio: 120.0,
    reason: "어떠한 사업을 위한 지출입니다.",
    status: DocumentReviewStatusEnum.Progress,
    review: "",
  },
  {
    code: 601,
    id: 3,
    rowId: 3,
    budgetDomain: BudgetDomainEnum.Autonomous,
    budgetDivisionExpenditure: BudgetDivisionExpenseEnum.Operating,
    projectName: "어떠한 사업",
    item: BudgetClassExpenseEnum.Product,
    lastYear: "500000",
    thisYear: "600000",
    ratio: 120.0,
    reason: "어떠한 사업을 위한 지출입니다.",
    status: DocumentReviewStatusEnum.Accepted,
    review: "",
  },
  {
    code: 502,
    id: 4,
    rowId: 4,
    budgetDomain: BudgetDomainEnum.School,
    budgetDivisionExpenditure: BudgetDivisionExpenseEnum.New,
    projectName: "학기 초 오리엔테이션",
    item: BudgetClassExpenseEnum.Supply,
    lastYear: "0",
    thisYear: "300000",
    ratio: null,
    reason: "기념품 및 물품 제작",
    status: DocumentReviewStatusEnum.Progress,
    review: "",
  },
  {
    code: 503,
    id: 5,
    rowId: 5,
    budgetDomain: BudgetDomainEnum.School,
    budgetDivisionExpenditure: BudgetDivisionExpenseEnum.New,
    projectName: "학기 초 오리엔테이션",
    item: BudgetClassExpenseEnum.Labor,
    lastYear: "0",
    thisYear: "200000",
    ratio: null,
    reason: "행사 대행 업체 섭외 비용",
    status: DocumentReviewStatusEnum.Progress,
    review: "",
  },
  {
    code: 504,
    id: 6,
    rowId: 6,
    budgetDomain: BudgetDomainEnum.School,
    budgetDivisionExpenditure: BudgetDivisionExpenseEnum.New,
    projectName: "중간고사 집중 학습 지원",
    item: BudgetClassExpenseEnum.Supply,
    lastYear: "0",
    thisYear: "150000",
    ratio: null,
    reason: "조명 개선",
    status: DocumentReviewStatusEnum.Progress,
    review: "",
  },
  {
    code: 505,
    id: 7,
    rowId: 7,
    budgetDomain: BudgetDomainEnum.School,
    budgetDivisionExpenditure: BudgetDivisionExpenseEnum.New,
    projectName: "중간고사 집중 학습 지원",
    item: BudgetClassExpenseEnum.Supply,
    lastYear: "0",
    thisYear: "250000",
    ratio: null,
    reason: "스터디존 확보",
    status: DocumentReviewStatusEnum.Progress,
    review: "",
  },
  {
    code: 506,
    id: 8,
    rowId: 8,
    budgetDomain: BudgetDomainEnum.School,
    budgetDivisionExpenditure: BudgetDivisionExpenseEnum.New,
    projectName: "중간고사 집중 학습 지원",
    item: BudgetClassExpenseEnum.Product,
    lastYear: "0",
    thisYear: "100000",
    ratio: null,
    reason: "간식 제공",
    status: DocumentReviewStatusEnum.Progress,
    review: "",
  },
  {
    code: 602,
    id: 9,
    rowId: 9,
    budgetDomain: BudgetDomainEnum.Autonomous,
    budgetDivisionExpenditure: BudgetDivisionExpenseEnum.Operating,
    projectName: "학생회 문화의 밤",
    item: BudgetClassExpenseEnum.Welfare,
    lastYear: "0",
    thisYear: "400000",
    ratio: null,
    reason: "행사 기획 및 운영",
    status: DocumentReviewStatusEnum.Progress,
    review: "",
  },
  {
    code: 603,
    id: 10,
    rowId: 10,
    budgetDomain: BudgetDomainEnum.Autonomous,
    budgetDivisionExpenditure: BudgetDivisionExpenseEnum.Operating,
    projectName: "학생회 문화의 밤",
    item: BudgetClassExpenseEnum.Product,
    lastYear: "0",
    thisYear: "200000",
    ratio: null,
    reason: "행사 홍보 및 소품 구입",
    status: DocumentReviewStatusEnum.Progress,
    review: "",
  },
];

export const mockManagerProjectNameCandidateList: ProjectNameCandidate[] =
  // 사업 계획서에서 작성된
  Object.values(BudgetDomainEnum).flatMap(domain =>
    Object.values(BudgetDivisionExpenseEnum).map(division => {
      const matchedTitles = ProjectProposalSingleContent.filter(content =>
        mockDBExpenditureData.some(
          exp =>
            exp.projectName === content.title &&
            exp.budgetDomain === domain &&
            exp.budgetDivisionExpenditure === division,
        ),
      ).map(content => content.title);

      return {
        budgetDomain: domain as BudgetDomainEnum,
        budgetDivisionExpenditure: division as BudgetDivisionExpenseEnum,
        projectNameCandidate: matchedTitles,
      };
    }),
  );
